# Generated by Django 3.1.1 on 2020-12-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.IntegerField()),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
