# Generated by Django 3.1.1 on 2020-12-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='RID',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
