# Generated by Django 3.1.1 on 2020-12-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201212_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='RID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
