# Generated by Django 3.1.1 on 2020-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201213_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Ftype',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='Stype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
