# Generated by Django 3.1.1 on 2020-12-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_studentmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='RgID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
